name: google_place
description: A new Flutter package for handle google place api that place search and details and photos and autocomplete and query autocomplete requests are available
version: 0.4.7
homepage: https://github.com/bazrafkan/google_place

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build_runner: ^2.3.0
  http: ^0.13.3
  json_annotation: ^4.7.0
  json_serializable: ^6.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
